### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by NikaOlve** [2019-a-gr2-moviles/Inmocasas-Grupo-Morales-Olmedo#3]
## Criterio de Aceptación
-   Los campos del formulario de ingreso son obligatorio y si el usuario ingresa las credenciales válidas accederá a la aplicación. 
-    Caso contrario: 
      -    **_Usuario o Contraseño vacíos_**: La aplicación muestra mensaje de Error
      -    **_Usuario o Contraseña erróneos_**: La aplicación muestra mensaje de Error
      -    **_Usuario no Registrado_**: La aplicación muestra mensaje de Información

- desde la pantalla de login se puede acceder a la pantalla de registro a través de un botón.

**Comment by JennyCastro** [comment]
### Usuario no Registrado: La aplicación muestra mensaje de Información
Qué dirá el mensaje de información
