### ISSUE TITLE
Buscar Publicaciones

### ISSUE THREAD

**Issue by NikaOlve** [2019-a-gr2-moviles/Inmocasas-Grupo-Morales-Olmedo#4]
## Criterio de Aceptación
-    Se mostrará las publicaciones de la ciudad ingresada con su respectiva información.
-    Solo valido para las ciudades que se estén en la asignadas en la aplicación "Ecuador"

**Comment by JennyCastro** [comment]
### Se mostrará las publicaciones de la ciudad ingresada con su respectiva información.
Formular de mejor manera el criterio de aceptación, muestra ambigüedad
