### ISSUE TITLE
Modificar Publicación

### ISSUE THREAD

**Issue by NikaOlve** [2019-a-gr2-moviles/Inmocasas-Grupo-Morales-Olmedo#6]
## Criterios de Aceptación
-    Si todos los datos ingresados en el formulario de actualización son válidos, al momento de guardar la información en la aplicación se visualizará en pantalla el mensaje: “La actualización se ha realizado satisfactoriamente”

**Comment by JennyCastro** [comment]
1. Cuales son los datos a ingresar en el formulario de actualización
2. Especificar cuando un datos es válido
